name: MovieInfoCI
on:
  push:
    branches:
      - main
jobs:
  build: 
    runs-on:  ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots package
      - name: Make directory named staging
        run: mkdir staging && cp movie-info-postgres/target/*.jar staging
      - uses: actions/upload-artifact@v3
        with:
          name: Package
          path: staging

      # - name: Release to S3
      #   run: bash scripts/pipeline/release.sh "src/main/java/io/javabrains/movieinfoservice/models/Movie.java" "my-storage-v1" "target"